---
version: "3.8"
services:
  discord-bot:
    image: throdax/verniy-bot:latest    
    container_name: discord-bot
    user: "1000:1000"
    restart: always
    network_mode: "host"
    volumes:
      # files
      - ./.env:/app/.env
      - ./config.yaml:/app/config.yaml      
      - ./src:/app/src
      # dir
      - ./logs:/app/logs
      - ./db:/app/db
    command: sh -c "npm run deploy-commands && npm start"
    
